version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moa_app
    ports:
      - "3000:3000"
    env_file:
      - .env.local # ↙︎ 로컬 개발용
    depends_on:
      - db
    volumes: # 코드 핫-리로드(선택)
      - .:/app
      - /app/node_modules # 호스트 node_modules 덮어쓰기 방지
    command: npm run dev # dev 모드 + HMR

  db:
    image: mysql:8.0
    container_name: moa_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moamoa
      MYSQL_USER: moa
      MYSQL_PASSWORD: moa
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
