//목업 친구 관계
export const mockFriendships = [
  {
    id: 1,
    userAId: "user999",
    userBId: "user123",
    status: "ACCEPTED",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    userAId: "user456",
    userBId: "user999",
    status: "ACCEPTED",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    userAId: "user999",
    userBId: "user112",
    status: "ACCEPTED",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
//목업 유저 목록
export const mockUsers = [
  {
    id: "user123",
    nickname: "서머",
    profileImage:
      "https://i.pinimg.com/736x/10/72/7c/10727cc6fbcb8a5b733c329177b0b6e7.jpg",
  },
  {
    id: "user456",
    nickname: "현머",
    profileImage:
      "https://i.pinimg.com/736x/26/3c/62/263c62bb7d1d67d8695a40f7e0263b3f.jpg",
  },
  {
    id: "user112",
    nickname: "미머",
    profileImage:
      "https://i.pinimg.com/736x/8a/eb/31/8aeb31f033ba256a88ae23351efdce4d.jpg",
  },
  {
    id: "user223",
    nickname: "멈멈머머머머머머머",
    profileImage:
      "https://i.pinimg.com/736x/22/7d/8b/227d8bb55e508cfce61a8d389dfdeec1.jpg",
  },
];

export const mockNotifications = [
  //내 소식 알림
  {
    id: 1,
    userId: "user123",
    type: "INVITE_GROUP_MOA",
    message: "님이 새로운 그룹 모아에 초대했습니다.",
    payload: "",
    read: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    userId: "user456",
    type: "FRIEND_REQUEST",
    message: "님이 친구 요청을 보냈습니다.",
    payload: "",
    read: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 21,
    userId: "user112",
    type: "FRIEND_REQUEST",
    message: "님이 친구 요청을 보냈습니다.",
    payload: "",
    read: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 221,
    userId: "user223",
    type: "FRIEND_REQUEST",
    message: "님이 친구 요청을 보냈습니다.",
    payload: "",
    read: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  //모아 소식 알림림
  {
    id: 3,
    userId: "admin",
    type: "LETTER_RECEIVED",
    message: "우와! 편지 한 통을 받으셨어요!",
    payload: "",
    read: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 4,
    userId: "admin",
    type: "FROM_MOA",
    message: "회원 가입을 축하드려요! 모아모아와 함께 추억을 모아봐요",
    payload: "",
    read: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 5,
    userId: "admin",
    type: "FROM_MOA",
    message: "회원 가입을 축하드려요! 모아모아와 함께 추억을 모아봐요",
    payload: "",
    read: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 6,
    userId: "admin",
    type: "FROM_MOA",
    message: "회원 가입을 축하드려요! 모아모아와 함께 추억을 모아봐요",
    payload: "",
    read: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 7,
    userId: "admin",
    type: "FROM_MOA",
    message: "회원 가입을 축하드려요! 모아모아와 함께 추억을 모아봐요",
    payload: "",
    read: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 8,
    userId: "admin",
    type: "FROM_MOA",
    message: "회원 가입을 축하드려요! 모아모아와 함께 추억을 모아봐요",
    payload: "",
    read: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 9,
    userId: "admin",
    type: "FROM_MOA",
    message: "회원 가입을 축하드려요! 모아모아와 함께 추억을 모아봐요",
    payload: "",
    read: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 10,
    userId: "admin",
    type: "FROM_MOA",
    message: "회원 가입을 축하드려요! 모아모아와 함께 추억을 모아봐요",
    payload: "",
    read: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 11,
    userId: "admin",
    type: "FROM_MOA",
    message: "회원 가입을 축하드려요! 모아모아와 함께 추억을 모아봐요",
    payload: "",
    read: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
